package(default_visibility=["//visibility:public"])

cc_library(
    name = "Box2D",
    hdrs = [
        "Box2D.h",
    ],
    srcs = [
    ],
    deps = [
        "//Box2D/Collision:Collision",
        "//Box2D/Common:Common",
        "//Box2D/Common:Draw",
        "//Box2D/Dynamics:Dynamics",
        "//Box2D/Particle:Particle",
        "//Box2D/Rope:Rope",
    ],
)
