package(default_visibility=["//visibility:public"])

cc_library(
    name = "Rope",
    hdrs = [
        "b2Rope.h",
    ],
    srcs = [
        "b2Rope.cpp",
    ],
    deps = [
        "//Box2D/Common:Common",
        "//Box2D/Common:Draw",
    ],
)
